apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 199103129564.dkr.ecr.us-east-2.amazonaws.com/demo-frontend
  newName: 199103129564.dkr.ecr.us-east-2.amazonaws.com/demo-frontend
  newTag: b34f9650
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
